// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albuns.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const contarFotografiasPorAlbum = `-- name: ContarFotografiasPorAlbum :one
SELECT COUNT(*) FROM fotografias
WHERE id_album = $1 AND ativo = TRUE
`

func (q *Queries) ContarFotografiasPorAlbum(ctx context.Context, idAlbum int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, contarFotografiasPorAlbum, idAlbum)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarPedidosDaFotografia = `-- name: ContarPedidosDaFotografia :one
SELECT COUNT(*) FROM pedidos_fotos WHERE id_fotografia = $1
`

func (q *Queries) ContarPedidosDaFotografia(ctx context.Context, idFotografia int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, contarPedidosDaFotografia, idFotografia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarAlbum = `-- name: CriarAlbum :one
INSERT INTO albuns (titulo, descricao, data_evento, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url
`

type CriarAlbumParams struct {
	Titulo                  string
	Descricao               sql.NullString
	DataEvento              time.Time
	IDFotografo             int64
	Lote                    bool
	ValorAlbum              string
	ValorUnitarioFotografia string
	Publico                 bool
}

func (q *Queries) CriarAlbum(ctx context.Context, arg CriarAlbumParams) (Albun, error) {
	row := q.db.QueryRowContext(ctx, criarAlbum,
		arg.Titulo,
		arg.Descricao,
		arg.DataEvento,
		arg.IDFotografo,
		arg.Lote,
		arg.ValorAlbum,
		arg.ValorUnitarioFotografia,
		arg.Publico,
	)
	var i Albun
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.DataEvento,
		&i.CriadoEm,
		&i.Ativo,
		&i.IDFotografo,
		&i.Lote,
		&i.ValorAlbum,
		&i.ValorUnitarioFotografia,
		&i.Publico,
		&i.CapaUrl,
	)
	return i, err
}

const criarFotografia = `-- name: CriarFotografia :one

INSERT INTO fotografias (url_alta, url_baixa, descricao, id_fotografo, id_album, valor_unitario)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, url_alta, url_baixa, descricao, id_fotografo, id_album, valor_unitario, ativo, criado_em, ordem
`

type CriarFotografiaParams struct {
	UrlAlta       string
	UrlBaixa      string
	Descricao     sql.NullString
	IDFotografo   int64
	IDAlbum       int64
	ValorUnitario string
}

// ─── Fotografias ──────────────────────────────────────────────────────────────
func (q *Queries) CriarFotografia(ctx context.Context, arg CriarFotografiaParams) (Fotografia, error) {
	row := q.db.QueryRowContext(ctx, criarFotografia,
		arg.UrlAlta,
		arg.UrlBaixa,
		arg.Descricao,
		arg.IDFotografo,
		arg.IDAlbum,
		arg.ValorUnitario,
	)
	var i Fotografia
	err := row.Scan(
		&i.ID,
		&i.UrlAlta,
		&i.UrlBaixa,
		&i.Descricao,
		&i.IDFotografo,
		&i.IDAlbum,
		&i.ValorUnitario,
		&i.Ativo,
		&i.CriadoEm,
		&i.Ordem,
	)
	return i, err
}

const deletarFotografia = `-- name: DeletarFotografia :exec
DELETE FROM fotografias WHERE id = $1
`

func (q *Queries) DeletarFotografia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletarFotografia, id)
	return err
}

const desativarFotografia = `-- name: DesativarFotografia :exec
UPDATE fotografias SET ativo = FALSE WHERE id = $1
`

func (q *Queries) DesativarFotografia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, desativarFotografia, id)
	return err
}

const listarAlbunsColaborador = `-- name: ListarAlbunsColaborador :many
SELECT a.id, a.titulo, a.descricao, a.data_evento, a.criado_em, a.ativo, a.id_fotografo, a.lote, a.valor_album, a.valor_unitario_fotografia, a.publico, a.capa_url
FROM albuns a
INNER JOIN fotografos_albuns fa ON fa.id_album = a.id
WHERE fa.id_fotografo = $1 AND a.ativo = TRUE
ORDER BY a.criado_em DESC
`

func (q *Queries) ListarAlbunsColaborador(ctx context.Context, idFotografo int64) ([]Albun, error) {
	rows, err := q.db.QueryContext(ctx, listarAlbunsColaborador, idFotografo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Albun
	for rows.Next() {
		var i Albun
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.DataEvento,
			&i.CriadoEm,
			&i.Ativo,
			&i.IDFotografo,
			&i.Lote,
			&i.ValorAlbum,
			&i.ValorUnitarioFotografia,
			&i.Publico,
			&i.CapaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAlbunsPorCliente = `-- name: ListarAlbunsPorCliente :many
SELECT a.id, a.titulo, a.descricao, a.data_evento, a.criado_em, a.ativo, a.id_fotografo, a.lote, a.valor_album, a.valor_unitario_fotografia, a.publico, a.capa_url
FROM albuns a
INNER JOIN clientes_albuns ca ON ca.id_album = a.id
WHERE ca.id_cliente = $1 AND a.ativo = TRUE
ORDER BY a.criado_em DESC
`

func (q *Queries) ListarAlbunsPorCliente(ctx context.Context, idCliente int64) ([]Albun, error) {
	rows, err := q.db.QueryContext(ctx, listarAlbunsPorCliente, idCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Albun
	for rows.Next() {
		var i Albun
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.DataEvento,
			&i.CriadoEm,
			&i.Ativo,
			&i.IDFotografo,
			&i.Lote,
			&i.ValorAlbum,
			&i.ValorUnitarioFotografia,
			&i.Publico,
			&i.CapaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAlbunsPorFotografo = `-- name: ListarAlbunsPorFotografo :many
SELECT id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url FROM albuns
WHERE id_fotografo = $1 AND ativo = TRUE
ORDER BY criado_em DESC
`

func (q *Queries) ListarAlbunsPorFotografo(ctx context.Context, idFotografo int64) ([]Albun, error) {
	rows, err := q.db.QueryContext(ctx, listarAlbunsPorFotografo, idFotografo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Albun
	for rows.Next() {
		var i Albun
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.DataEvento,
			&i.CriadoEm,
			&i.Ativo,
			&i.IDFotografo,
			&i.Lote,
			&i.ValorAlbum,
			&i.ValorUnitarioFotografia,
			&i.Publico,
			&i.CapaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAlbunsPublicos = `-- name: ListarAlbunsPublicos :many
SELECT id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url FROM albuns
WHERE publico = TRUE AND ativo = TRUE
ORDER BY criado_em DESC
`

func (q *Queries) ListarAlbunsPublicos(ctx context.Context) ([]Albun, error) {
	rows, err := q.db.QueryContext(ctx, listarAlbunsPublicos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Albun
	for rows.Next() {
		var i Albun
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.DataEvento,
			&i.CriadoEm,
			&i.Ativo,
			&i.IDFotografo,
			&i.Lote,
			&i.ValorAlbum,
			&i.ValorUnitarioFotografia,
			&i.Publico,
			&i.CapaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarAlbunsPublicosPorFotografo = `-- name: ListarAlbunsPublicosPorFotografo :many
SELECT id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url FROM albuns
WHERE publico = TRUE AND ativo = TRUE AND id_fotografo = $1
ORDER BY criado_em DESC
`

func (q *Queries) ListarAlbunsPublicosPorFotografo(ctx context.Context, idFotografo int64) ([]Albun, error) {
	rows, err := q.db.QueryContext(ctx, listarAlbunsPublicosPorFotografo, idFotografo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Albun
	for rows.Next() {
		var i Albun
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.DataEvento,
			&i.CriadoEm,
			&i.Ativo,
			&i.IDFotografo,
			&i.Lote,
			&i.ValorAlbum,
			&i.ValorUnitarioFotografia,
			&i.Publico,
			&i.CapaUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFotografiasPorAlbum = `-- name: ListarFotografiasPorAlbum :many
SELECT id, url_alta, url_baixa, descricao, id_fotografo, id_album, valor_unitario, ativo, criado_em, ordem FROM fotografias
WHERE id_album = $1 AND ativo = TRUE
ORDER BY ordem ASC, id ASC
`

func (q *Queries) ListarFotografiasPorAlbum(ctx context.Context, idAlbum int64) ([]Fotografia, error) {
	rows, err := q.db.QueryContext(ctx, listarFotografiasPorAlbum, idAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fotografia
	for rows.Next() {
		var i Fotografia
		if err := rows.Scan(
			&i.ID,
			&i.UrlAlta,
			&i.UrlBaixa,
			&i.Descricao,
			&i.IDFotografo,
			&i.IDAlbum,
			&i.ValorUnitario,
			&i.Ativo,
			&i.CriadoEm,
			&i.Ordem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterAlbumPorID = `-- name: ObterAlbumPorID :one
SELECT id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url FROM albuns
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) ObterAlbumPorID(ctx context.Context, id int64) (Albun, error) {
	row := q.db.QueryRowContext(ctx, obterAlbumPorID, id)
	var i Albun
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.DataEvento,
		&i.CriadoEm,
		&i.Ativo,
		&i.IDFotografo,
		&i.Lote,
		&i.ValorAlbum,
		&i.ValorUnitarioFotografia,
		&i.Publico,
		&i.CapaUrl,
	)
	return i, err
}

const obterAlbumPublico = `-- name: ObterAlbumPublico :one
SELECT id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url FROM albuns
WHERE id = $1 AND publico = TRUE AND ativo = TRUE
`

func (q *Queries) ObterAlbumPublico(ctx context.Context, id int64) (Albun, error) {
	row := q.db.QueryRowContext(ctx, obterAlbumPublico, id)
	var i Albun
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.DataEvento,
		&i.CriadoEm,
		&i.Ativo,
		&i.IDFotografo,
		&i.Lote,
		&i.ValorAlbum,
		&i.ValorUnitarioFotografia,
		&i.Publico,
		&i.CapaUrl,
	)
	return i, err
}

const obterFotografiaPorID = `-- name: ObterFotografiaPorID :one
SELECT id, url_alta, url_baixa, descricao, id_fotografo, id_album, valor_unitario, ativo, criado_em, ordem FROM fotografias WHERE id = $1
`

func (q *Queries) ObterFotografiaPorID(ctx context.Context, id int64) (Fotografia, error) {
	row := q.db.QueryRowContext(ctx, obterFotografiaPorID, id)
	var i Fotografia
	err := row.Scan(
		&i.ID,
		&i.UrlAlta,
		&i.UrlBaixa,
		&i.Descricao,
		&i.IDFotografo,
		&i.IDAlbum,
		&i.ValorUnitario,
		&i.Ativo,
		&i.CriadoEm,
		&i.Ordem,
	)
	return i, err
}

const associarClienteAlbum = `-- name: associarClienteAlbum :one

INSERT INTO clientes_albuns (id_cliente, id_album)
VALUES ($1, $2)
ON CONFLICT (id_cliente, id_album) DO NOTHING
RETURNING id, id_cliente, id_album, criado_em
`

type associarClienteAlbumParams struct {
	IDCliente int64
	IDAlbum   int64
}

// ─── Clientes ─────────────────────────────────────────────────────────────────
func (q *Queries) associarClienteAlbum(ctx context.Context, arg associarClienteAlbumParams) (ClientesAlbun, error) {
	row := q.db.QueryRowContext(ctx, associarClienteAlbum, arg.IDCliente, arg.IDAlbum)
	var i ClientesAlbun
	err := row.Scan(
		&i.ID,
		&i.IDCliente,
		&i.IDAlbum,
		&i.CriadoEm,
	)
	return i, err
}

const atualizarCapaAlbum = `-- name: atualizarCapaAlbum :one
UPDATE albuns SET capa_url = $2 WHERE id = $1
RETURNING id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url
`

type atualizarCapaAlbumParams struct {
	ID      int64
	CapaUrl sql.NullString
}

func (q *Queries) atualizarCapaAlbum(ctx context.Context, arg atualizarCapaAlbumParams) (Albun, error) {
	row := q.db.QueryRowContext(ctx, atualizarCapaAlbum, arg.ID, arg.CapaUrl)
	var i Albun
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.DataEvento,
		&i.CriadoEm,
		&i.Ativo,
		&i.IDFotografo,
		&i.Lote,
		&i.ValorAlbum,
		&i.ValorUnitarioFotografia,
		&i.Publico,
		&i.CapaUrl,
	)
	return i, err
}

const atualizarOrdemFotografia = `-- name: atualizarOrdemFotografia :exec
UPDATE fotografias SET ordem = $3 WHERE id = $1 AND id_album = $2
`

type atualizarOrdemFotografiaParams struct {
	ID      int64
	IDAlbum int64
	Ordem   int64
}

func (q *Queries) atualizarOrdemFotografia(ctx context.Context, arg atualizarOrdemFotografiaParams) error {
	_, err := q.db.ExecContext(ctx, atualizarOrdemFotografia, arg.ID, arg.IDAlbum, arg.Ordem)
	return err
}

const atualizarPublicoAlbum = `-- name: atualizarPublicoAlbum :one
UPDATE albuns SET publico = $2 WHERE id = $1
RETURNING id, titulo, descricao, data_evento, criado_em, ativo, id_fotografo, lote, valor_album, valor_unitario_fotografia, publico, capa_url
`

type atualizarPublicoAlbumParams struct {
	ID      int64
	Publico bool
}

func (q *Queries) atualizarPublicoAlbum(ctx context.Context, arg atualizarPublicoAlbumParams) (Albun, error) {
	row := q.db.QueryRowContext(ctx, atualizarPublicoAlbum, arg.ID, arg.Publico)
	var i Albun
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.DataEvento,
		&i.CriadoEm,
		&i.Ativo,
		&i.IDFotografo,
		&i.Lote,
		&i.ValorAlbum,
		&i.ValorUnitarioFotografia,
		&i.Publico,
		&i.CapaUrl,
	)
	return i, err
}

const listarFotografiasPorAlbumPaginado = `-- name: listarFotografiasPorAlbumPaginado :many
SELECT id, url_alta, url_baixa, descricao, id_fotografo, id_album, valor_unitario, ativo, criado_em, ordem FROM fotografias
WHERE id_album = $1 AND ativo = TRUE
ORDER BY ordem ASC, id ASC
LIMIT $2 OFFSET $3
`

type listarFotografiasPorAlbumPaginadoParams struct {
	IDAlbum int64
	Limit   int32
	Offset  int32
}

func (q *Queries) listarFotografiasPorAlbumPaginado(ctx context.Context, arg listarFotografiasPorAlbumPaginadoParams) ([]Fotografia, error) {
	rows, err := q.db.QueryContext(ctx, listarFotografiasPorAlbumPaginado, arg.IDAlbum, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fotografia
	for rows.Next() {
		var i Fotografia
		if err := rows.Scan(
			&i.ID,
			&i.UrlAlta,
			&i.UrlBaixa,
			&i.Descricao,
			&i.IDFotografo,
			&i.IDAlbum,
			&i.ValorUnitario,
			&i.Ativo,
			&i.CriadoEm,
			&i.Ordem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verificarAcessoClienteAlbum = `-- name: verificarAcessoClienteAlbum :one
SELECT EXISTS(
  SELECT 1 FROM clientes_albuns WHERE id_cliente = $1 AND id_album = $2
)
`

type verificarAcessoClienteAlbumParams struct {
	IDCliente int64
	IDAlbum   int64
}

func (q *Queries) verificarAcessoClienteAlbum(ctx context.Context, arg verificarAcessoClienteAlbumParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, verificarAcessoClienteAlbum, arg.IDCliente, arg.IDAlbum)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verificarConvitePendente = `-- name: verificarConvitePendente :one
SELECT EXISTS(
  SELECT 1 FROM convites
  WHERE email = $1 AND id_album = $2 AND used_at IS NULL AND expires_at > NOW()
)
`

type verificarConvitePendenteParams struct {
	Email   string
	IDAlbum int64
}

func (q *Queries) verificarConvitePendente(ctx context.Context, arg verificarConvitePendenteParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, verificarConvitePendente, arg.Email, arg.IDAlbum)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
