// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clientes_albuns.sql

package db

import (
	"context"
	"time"
)

const listarClientesAlbum = `-- name: ListarClientesAlbum :many
SELECT ca.id, ca.id_cliente, ca.id_album, u.nome, u.email, ca.criado_em
FROM clientes_albuns ca
INNER JOIN usuarios u ON u.id = ca.id_cliente
WHERE ca.id_album = $1 AND u.ativo = TRUE
ORDER BY ca.criado_em ASC
`

type ListarClientesAlbumRow struct {
	ID        int64
	IDCliente int64
	IDAlbum   int64
	Nome      string
	Email     string
	CriadoEm  time.Time
}

func (q *Queries) ListarClientesAlbum(ctx context.Context, idAlbum int64) ([]ListarClientesAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listarClientesAlbum, idAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarClientesAlbumRow
	for rows.Next() {
		var i ListarClientesAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.IDCliente,
			&i.IDAlbum,
			&i.Nome,
			&i.Email,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerClienteAlbum = `-- name: removerClienteAlbum :exec
DELETE FROM clientes_albuns WHERE id = $1 AND id_album = $2
`

type removerClienteAlbumParams struct {
	ID      int64
	IDAlbum int64
}

func (q *Queries) removerClienteAlbum(ctx context.Context, arg removerClienteAlbumParams) error {
	_, err := q.db.ExecContext(ctx, removerClienteAlbum, arg.ID, arg.IDAlbum)
	return err
}
