// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fotografos_albuns.sql

package db

import (
	"context"
	"time"
)

const listarFotografosAlbum = `-- name: ListarFotografosAlbum :many
SELECT fa.id, fa.id_fotografo, fa.id_album, u.nome, u.email, fa.criado_em
FROM fotografos_albuns fa
INNER JOIN usuarios u ON u.id = fa.id_fotografo
WHERE fa.id_album = $1 AND u.ativo = TRUE
ORDER BY fa.criado_em ASC
`

type ListarFotografosAlbumRow struct {
	ID          int64
	IDFotografo int64
	IDAlbum     int64
	Nome        string
	Email       string
	CriadoEm    time.Time
}

func (q *Queries) ListarFotografosAlbum(ctx context.Context, idAlbum int64) ([]ListarFotografosAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listarFotografosAlbum, idAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarFotografosAlbumRow
	for rows.Next() {
		var i ListarFotografosAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.IDFotografo,
			&i.IDAlbum,
			&i.Nome,
			&i.Email,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const associarFotografoAlbum = `-- name: associarFotografoAlbum :one
INSERT INTO fotografos_albuns (id_fotografo, id_album)
VALUES ($1, $2)
ON CONFLICT (id_fotografo, id_album) DO NOTHING
RETURNING id, id_fotografo, id_album, criado_em
`

type associarFotografoAlbumParams struct {
	IDFotografo int64
	IDAlbum     int64
}

func (q *Queries) associarFotografoAlbum(ctx context.Context, arg associarFotografoAlbumParams) (FotografosAlbun, error) {
	row := q.db.QueryRowContext(ctx, associarFotografoAlbum, arg.IDFotografo, arg.IDAlbum)
	var i FotografosAlbun
	err := row.Scan(
		&i.ID,
		&i.IDFotografo,
		&i.IDAlbum,
		&i.CriadoEm,
	)
	return i, err
}

const removerFotografoAlbum = `-- name: removerFotografoAlbum :exec
DELETE FROM fotografos_albuns WHERE id = $1 AND id_album = $2
`

type removerFotografoAlbumParams struct {
	ID      int64
	IDAlbum int64
}

func (q *Queries) removerFotografoAlbum(ctx context.Context, arg removerFotografoAlbumParams) error {
	_, err := q.db.ExecContext(ctx, removerFotografoAlbum, arg.ID, arg.IDAlbum)
	return err
}

const verificarFotografoAlbum = `-- name: verificarFotografoAlbum :one
SELECT EXISTS(
  SELECT 1 FROM fotografos_albuns WHERE id_fotografo = $1 AND id_album = $2
)
`

type verificarFotografoAlbumParams struct {
	IDFotografo int64
	IDAlbum     int64
}

func (q *Queries) verificarFotografoAlbum(ctx context.Context, arg verificarFotografoAlbumParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, verificarFotografoAlbum, arg.IDFotografo, arg.IDAlbum)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
