// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fotografos.sql

package db

import (
	"context"
)

const criarFotografo = `-- name: CriarFotografo :one
INSERT INTO fotografos (nome, email, senha_hash)
VALUES ($1, $2, $3)
RETURNING id, nome, email, senha_hash, criado_em
`

type CriarFotografoParams struct {
	Nome      string
	Email     string
	SenhaHash string
}

func (q *Queries) CriarFotografo(ctx context.Context, arg CriarFotografoParams) (Fotografo, error) {
	row := q.db.QueryRowContext(ctx, criarFotografo, arg.Nome, arg.Email, arg.SenhaHash)
	var i Fotografo
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}

const obterFotografoPorEmail = `-- name: ObterFotografoPorEmail :one
SELECT id, nome, email, senha_hash, criado_em FROM fotografos
WHERE email = $1 LIMIT 1
`

func (q *Queries) ObterFotografoPorEmail(ctx context.Context, email string) (Fotografo, error) {
	row := q.db.QueryRowContext(ctx, obterFotografoPorEmail, email)
	var i Fotografo
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.CriadoEm,
	)
	return i, err
}
