// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Fotografo struct {
	ID        int64
	Nome      string
	Email     string
	SenhaHash string
	CriadoEm  time.Time
}
