// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pedidos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listarFotosPedido = `-- name: ListarFotosPedido :many
SELECT pf.id, pf.id_pedido, pf.id_fotografia, pf.valor_unitario,
       f.url_alta, f.url_baixa
FROM pedidos_fotos pf
INNER JOIN fotografias f ON f.id = pf.id_fotografia
WHERE pf.id_pedido = $1
`

type ListarFotosPedidoRow struct {
	ID            int64
	IDPedido      int64
	IDFotografia  int64
	ValorUnitario string
	UrlAlta       string
	UrlBaixa      string
}

func (q *Queries) ListarFotosPedido(ctx context.Context, idPedido int64) ([]ListarFotosPedidoRow, error) {
	rows, err := q.db.QueryContext(ctx, listarFotosPedido, idPedido)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarFotosPedidoRow
	for rows.Next() {
		var i ListarFotosPedidoRow
		if err := rows.Scan(
			&i.ID,
			&i.IDPedido,
			&i.IDFotografia,
			&i.ValorUnitario,
			&i.UrlAlta,
			&i.UrlBaixa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosPorCliente = `-- name: ListarPedidosPorCliente :many
SELECT id, id_cliente, id_album, status, valor_total, criado_em, mp_preference_id, mp_payment_id FROM pedidos
WHERE id_cliente = $1
ORDER BY criado_em DESC
`

func (q *Queries) ListarPedidosPorCliente(ctx context.Context, idCliente int64) ([]Pedido, error) {
	rows, err := q.db.QueryContext(ctx, listarPedidosPorCliente, idCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(
			&i.ID,
			&i.IDCliente,
			&i.IDAlbum,
			&i.Status,
			&i.ValorTotal,
			&i.CriadoEm,
			&i.MpPreferenceID,
			&i.MpPaymentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosResumoPorCliente = `-- name: ListarPedidosResumoPorCliente :many
SELECT p.id, p.id_cliente, p.id_album, p.status, p.valor_total, p.criado_em,
       a.titulo AS album_titulo, a.capa_url,
       (SELECT COUNT(*) FROM pedidos_fotos pf WHERE pf.id_pedido = p.id) AS total_fotos
FROM pedidos p
INNER JOIN albuns a ON a.id = p.id_album
WHERE p.id_cliente = $1
ORDER BY p.criado_em DESC
`

type ListarPedidosResumoPorClienteRow struct {
	ID          int64
	IDCliente   int64
	IDAlbum     int64
	Status      string
	ValorTotal  string
	CriadoEm    time.Time
	AlbumTitulo string
	CapaUrl     sql.NullString
	TotalFotos  int64
}

func (q *Queries) ListarPedidosResumoPorCliente(ctx context.Context, idCliente int64) ([]ListarPedidosResumoPorClienteRow, error) {
	rows, err := q.db.QueryContext(ctx, listarPedidosResumoPorCliente, idCliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosResumoPorClienteRow
	for rows.Next() {
		var i ListarPedidosResumoPorClienteRow
		if err := rows.Scan(
			&i.ID,
			&i.IDCliente,
			&i.IDAlbum,
			&i.Status,
			&i.ValorTotal,
			&i.CriadoEm,
			&i.AlbumTitulo,
			&i.CapaUrl,
			&i.TotalFotos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterPedidoPorID = `-- name: ObterPedidoPorID :one
SELECT id, id_cliente, id_album, status, valor_total, criado_em, mp_preference_id, mp_payment_id FROM pedidos WHERE id = $1
`

func (q *Queries) ObterPedidoPorID(ctx context.Context, id int64) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, obterPedidoPorID, id)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.IDCliente,
		&i.IDAlbum,
		&i.Status,
		&i.ValorTotal,
		&i.CriadoEm,
		&i.MpPreferenceID,
		&i.MpPaymentID,
	)
	return i, err
}

const atualizarPreferenciaPedido = `-- name: atualizarPreferenciaPedido :exec
UPDATE pedidos SET mp_preference_id = $2 WHERE id = $1
`

type atualizarPreferenciaPedidoParams struct {
	ID             int64
	MpPreferenceID sql.NullString
}

func (q *Queries) atualizarPreferenciaPedido(ctx context.Context, arg atualizarPreferenciaPedidoParams) error {
	_, err := q.db.ExecContext(ctx, atualizarPreferenciaPedido, arg.ID, arg.MpPreferenceID)
	return err
}

const criarPedido = `-- name: criarPedido :one
INSERT INTO pedidos (id_cliente, id_album, status, valor_total)
VALUES ($1, $2, 'pendente', $3)
RETURNING id, id_cliente, id_album, status, valor_total, criado_em, mp_preference_id, mp_payment_id
`

type criarPedidoParams struct {
	IDCliente  int64
	IDAlbum    int64
	ValorTotal string
}

func (q *Queries) criarPedido(ctx context.Context, arg criarPedidoParams) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, criarPedido, arg.IDCliente, arg.IDAlbum, arg.ValorTotal)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.IDCliente,
		&i.IDAlbum,
		&i.Status,
		&i.ValorTotal,
		&i.CriadoEm,
		&i.MpPreferenceID,
		&i.MpPaymentID,
	)
	return i, err
}

const criarPedidoFoto = `-- name: criarPedidoFoto :exec
INSERT INTO pedidos_fotos (id_pedido, id_fotografia, valor_unitario)
VALUES ($1, $2, $3)
ON CONFLICT (id_pedido, id_fotografia) DO NOTHING
`

type criarPedidoFotoParams struct {
	IDPedido      int64
	IDFotografia  int64
	ValorUnitario string
}

func (q *Queries) criarPedidoFoto(ctx context.Context, arg criarPedidoFotoParams) error {
	_, err := q.db.ExecContext(ctx, criarPedidoFoto, arg.IDPedido, arg.IDFotografia, arg.ValorUnitario)
	return err
}

const listarFotoIDsCompradas = `-- name: listarFotoIDsCompradas :many
SELECT pf.id_fotografia
FROM pedidos_fotos pf
INNER JOIN pedidos p ON p.id = pf.id_pedido
WHERE p.id_cliente = $1 AND p.id_album = $2 AND p.status = 'pago'
`

type listarFotoIDsCompradasParams struct {
	IDCliente int64
	IDAlbum   int64
}

func (q *Queries) listarFotoIDsCompradas(ctx context.Context, arg listarFotoIDsCompradasParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listarFotoIDsCompradas, arg.IDCliente, arg.IDAlbum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id_fotografia int64
		if err := rows.Scan(&id_fotografia); err != nil {
			return nil, err
		}
		items = append(items, id_fotografia)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarPagamentoPedido = `-- name: registrarPagamentoPedido :exec
UPDATE pedidos SET status = $2, mp_payment_id = $3 WHERE id = $1
`

type registrarPagamentoPedidoParams struct {
	ID          int64
	Status      string
	MpPaymentID sql.NullString
}

func (q *Queries) registrarPagamentoPedido(ctx context.Context, arg registrarPagamentoPedidoParams) error {
	_, err := q.db.ExecContext(ctx, registrarPagamentoPedido, arg.ID, arg.Status, arg.MpPaymentID)
	return err
}
