// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package db

import (
	"context"
	"database/sql"
)

const criarCliente = `-- name: CriarCliente :one
INSERT INTO usuarios (nome, email, senha_hash, tipo, ativo)
VALUES ($1, $2, $3, 'cliente', TRUE)
RETURNING id, nome, email, senha_hash, ativo, criado_em, tipo, foto_perfil, bio
`

type CriarClienteParams struct {
	Nome      string
	Email     string
	SenhaHash sql.NullString
}

func (q *Queries) CriarCliente(ctx context.Context, arg CriarClienteParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, criarCliente, arg.Nome, arg.Email, arg.SenhaHash)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Ativo,
		&i.CriadoEm,
		&i.Tipo,
		&i.FotoPerfil,
		&i.Bio,
	)
	return i, err
}

const criarFotografo = `-- name: CriarFotografo :one
INSERT INTO usuarios (nome, email, senha_hash, tipo, ativo)
VALUES ($1, $2, $3, 'fotografo', TRUE)
RETURNING id, nome, email, senha_hash, ativo, criado_em, tipo, foto_perfil, bio
`

type CriarFotografoParams struct {
	Nome      string
	Email     string
	SenhaHash sql.NullString
}

func (q *Queries) CriarFotografo(ctx context.Context, arg CriarFotografoParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, criarFotografo, arg.Nome, arg.Email, arg.SenhaHash)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Ativo,
		&i.CriadoEm,
		&i.Tipo,
		&i.FotoPerfil,
		&i.Bio,
	)
	return i, err
}

const listarFotografosComAlbumPublico = `-- name: ListarFotografosComAlbumPublico :many
SELECT u.id, u.nome, u.foto_perfil, u.bio, COUNT(a.id) AS total_albuns
FROM usuarios u
INNER JOIN albuns a ON a.id_fotografo = u.id AND a.publico = TRUE AND a.ativo = TRUE
WHERE u.tipo = 'fotografo' AND u.ativo = TRUE
GROUP BY u.id, u.nome, u.foto_perfil, u.bio
ORDER BY total_albuns DESC
`

type ListarFotografosComAlbumPublicoRow struct {
	ID          int64
	Nome        string
	FotoPerfil  sql.NullString
	Bio         sql.NullString
	TotalAlbuns int64
}

func (q *Queries) ListarFotografosComAlbumPublico(ctx context.Context) ([]ListarFotografosComAlbumPublicoRow, error) {
	rows, err := q.db.QueryContext(ctx, listarFotografosComAlbumPublico)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarFotografosComAlbumPublicoRow
	for rows.Next() {
		var i ListarFotografosComAlbumPublicoRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.FotoPerfil,
			&i.Bio,
			&i.TotalAlbuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterFotografoPorEmail = `-- name: ObterFotografoPorEmail :one
SELECT id, nome, email, senha_hash, ativo, criado_em, tipo, foto_perfil, bio FROM usuarios
WHERE email = $1 AND tipo = 'fotografo' AND ativo = TRUE
LIMIT 1
`

func (q *Queries) ObterFotografoPorEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obterFotografoPorEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Ativo,
		&i.CriadoEm,
		&i.Tipo,
		&i.FotoPerfil,
		&i.Bio,
	)
	return i, err
}

const obterFotografoPorID = `-- name: ObterFotografoPorID :one
SELECT id, nome, email, senha_hash, ativo, criado_em, tipo, foto_perfil, bio FROM usuarios
WHERE id = $1 AND tipo = 'fotografo' AND ativo = TRUE
`

func (q *Queries) ObterFotografoPorID(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obterFotografoPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Ativo,
		&i.CriadoEm,
		&i.Tipo,
		&i.FotoPerfil,
		&i.Bio,
	)
	return i, err
}

const obterUsuarioPorEmail = `-- name: ObterUsuarioPorEmail :one
SELECT id, nome, email, senha_hash, ativo, criado_em, tipo, foto_perfil, bio FROM usuarios
WHERE email = $1 AND ativo = TRUE
LIMIT 1
`

func (q *Queries) ObterUsuarioPorEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obterUsuarioPorEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Ativo,
		&i.CriadoEm,
		&i.Tipo,
		&i.FotoPerfil,
		&i.Bio,
	)
	return i, err
}

const obterUsuarioPorID = `-- name: ObterUsuarioPorID :one
SELECT id, nome, email, senha_hash, ativo, criado_em, tipo, foto_perfil, bio FROM usuarios
WHERE id = $1 AND ativo = TRUE
`

func (q *Queries) ObterUsuarioPorID(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obterUsuarioPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Ativo,
		&i.CriadoEm,
		&i.Tipo,
		&i.FotoPerfil,
		&i.Bio,
	)
	return i, err
}

const atualizarBioFotografo = `-- name: atualizarBioFotografo :exec
UPDATE usuarios SET bio = $2 WHERE id = $1
`

type atualizarBioFotografoParams struct {
	ID  int64
	Bio sql.NullString
}

func (q *Queries) atualizarBioFotografo(ctx context.Context, arg atualizarBioFotografoParams) error {
	_, err := q.db.ExecContext(ctx, atualizarBioFotografo, arg.ID, arg.Bio)
	return err
}

const atualizarFotoPerfilFotografo = `-- name: atualizarFotoPerfilFotografo :exec
UPDATE usuarios SET foto_perfil = $2 WHERE id = $1
`

type atualizarFotoPerfilFotografoParams struct {
	ID         int64
	FotoPerfil sql.NullString
}

func (q *Queries) atualizarFotoPerfilFotografo(ctx context.Context, arg atualizarFotoPerfilFotografoParams) error {
	_, err := q.db.ExecContext(ctx, atualizarFotoPerfilFotografo, arg.ID, arg.FotoPerfil)
	return err
}
